# Generated by Django 4.2.11 on 2024-04-16 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageurl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='tag_id',
        ),
        migrations.CreateModel(
            name='UrlTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageurl.tag')),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageurl.url')),
            ],
            options={
                'db_table': 'url_tag',
            },
        ),
    ]
