# Generated by Django 4.2.11 on 2024-04-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageurl', '0002_remove_url_tag_id_urltag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urltag',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='urltag',
            old_name='url_id',
            new_name='url',
        ),
    ]
