# Generated by Django 4.2.11 on 2024-04-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageurl', '0004_logerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
